// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeY5wU-_Q6-3O6jPfWUehXNE7qJn6jepI',
    appId: '1:280580094097:web:0482cef8fa4f46f692a730',
    messagingSenderId: '280580094097',
    projectId: 'my-store-34750',
    authDomain: 'my-store-34750.firebaseapp.com',
    storageBucket: 'my-store-34750.firebasestorage.app',
    measurementId: 'G-E5G7Y83BXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgBte8fteHTV599JRB_M9UANoxSgFPCYY',
    appId: '1:280580094097:android:921f7eaf6523328392a730',
    messagingSenderId: '280580094097',
    projectId: 'my-store-34750',
    storageBucket: 'my-store-34750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBelGadbeawmDrA77OyrZA816Y7kioMAZ4',
    appId: '1:280580094097:ios:5bc43fd3d84cfec592a730',
    messagingSenderId: '280580094097',
    projectId: 'my-store-34750',
    storageBucket: 'my-store-34750.firebasestorage.app',
    iosBundleId: 'com.example.myStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBelGadbeawmDrA77OyrZA816Y7kioMAZ4',
    appId: '1:280580094097:ios:5bc43fd3d84cfec592a730',
    messagingSenderId: '280580094097',
    projectId: 'my-store-34750',
    storageBucket: 'my-store-34750.firebasestorage.app',
    iosBundleId: 'com.example.myStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeY5wU-_Q6-3O6jPfWUehXNE7qJn6jepI',
    appId: '1:280580094097:web:f29de1bfa07b64fe92a730',
    messagingSenderId: '280580094097',
    projectId: 'my-store-34750',
    authDomain: 'my-store-34750.firebaseapp.com',
    storageBucket: 'my-store-34750.firebasestorage.app',
    measurementId: 'G-NP1RD3GKLV',
  );
}
